---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - test.io.liwa.com
  resources:
  - wangresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.io.liwa.com
  resources:
  - wangresses/finalizers
  verbs:
  - update
- apiGroups:
  - test.io.liwa.com
  resources:
  - wangresses/status
  verbs:
  - get
  - patch
  - update
