# permissions for end users to view wangresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: wangress-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: wangress
    app.kubernetes.io/part-of: wangress
    app.kubernetes.io/managed-by: kustomize
  name: wangress-viewer-role
rules:
- apiGroups:
  - test.io.liwa.com
  resources:
  - wangresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.io.liwa.com
  resources:
  - wangresses/status
  verbs:
  - get
